import pandas as pd, matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
df = pd.read_csv("results/tables/pareto_tradeoff.csv")
fig, ax1 = plt.subplots(figsize=(7,5))
ax1.set_xlabel("Projection depth (rounds)")
ax1.set_ylabel("Classification accuracy", color="tab:green")
l1=ax1.plot(df["round"], df["class_acc"], "o-", color="tab:green", label="Classification accuracy")
ax1.axhline(1/7, ls="--", color="tab:green", alpha=0.5)
ax1.text(6, 1/7+0.02, "chance = 1/7", color="tab:green", fontsize=9)
ax1.tick_params(axis="y", labelcolor="tab:green")
ax1.set_ylim(0,0.75)
ax2 = ax1.twinx()
ax2.set_ylabel("MaxSkew (retrieval bias)", color="tab:red")
l2=ax2.plot(df["round"], df["maxskew"], "s-", color="tab:red", label="MaxSkew")
ax2.tick_params(axis="y", labelcolor="tab:red")
ax2.set_ylim(0, df["maxskew"].max()*1.1)
plt.title("Classification-Retrieval Trade-off (race, ViT-B/32)")
lines=l1+l2; ax1.legend(lines,[l.get_label() for l in lines],loc="center right")
plt.tight_layout()
plt.savefig("results/figures/pareto_tradeoff.png", dpi=200)
print("saved results/figures/pareto_tradeoff.png")
